version: "3.8"

services: 

  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=GiskardCalendarExercise
      - MYSQL_USER=giskard
      - MYSQL_PASSWORD=giskard
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - 3306

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    environment:
      - WAIT_HOSTS=mysql_server:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  